CREATE TABLE clients (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    cellphone VARCHAR(20) UNIQUE NOT NULL
);