CREATE TABLE client (
  	id SERIAL PRIMARY KEY,
  	name VARCHAR (100) NOT NULL,
  	cpf VARCHAR(11) UNIQUE NOT NULL,
  	email VARCHAR (150) UNIQUE NOT NULL,
  	cellphone VARCHAR(11) UNIQUE NOT NULL
  );