ALTER TABLE clients
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN name TYPE VARCHAR(150),
    ALTER COLUMN cpf SET NOT NULL,
    ALTER COLUMN cpf TYPE VARCHAR(11),
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN email TYPE VARCHAR(150),
    ALTER COLUMN cellphone SET NOT NULL,
    ALTER COLUMN cellphone TYPE VARCHAR(11);
